(package "define-it"
         "0.2.4"
         "Define, translate, wiki the word")

(package-file "define-it.el")

(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "s")
(depends-on "request")
(depends-on "popup")
(depends-on "pos-tip")
(depends-on "google-translate")
(depends-on "wiki-summary")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
